### ISSUE TITLE
Problem with zip file in your installation guide..

### ISSUE THREAD

**Issue by chsims1** [marco79cgn/radio-paradise#1]
wget https://github.com/marco79cgn/volumio-plugins/blob/master/plugins/music_service/radio_paradise/radio-paradise-volumio2-plugin-2018-05-06.zip

I couldn't unzip this file, but the dropbox one works fine.

**Comment by marco79cgn** [comment]
Hi,
thanks for the feedback. This is the wrong project here, this is the Browser version of Radio Paradise. ;)

The download link of the Volumio Plugin was wrong. I fixed it in the instructions. 

wget https://raw.githubusercontent.com/marco79cgn/volumio-plugins/master/plugins/music_service/radio_paradise/radio-paradise-volumio2-plugin-2018-05-06.zip
