### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Swipe650** [marco79cgn/radio-paradise#5]
Hi, I've had problems for the last few days. It fails to connect. Looks like a cors anwhere issue to me. I've seen this occasionally but never for this length of time.

**Comment by marco79cgn** [comment]
Hm, it works for me right now. It's true that it depends on the 3rd party service cors-anywhere. It's not in my hands. You could try an alternative if you like. Just replace `player.js` line 376
old:
`xhr.open('get', 'https://cors-anywhere.herokuapp.com/'+flacApiNextEventUrl, isNotBlocking);`
new:
`xhr.open('get', 'https://crossorigin.me/'+flacApiNextEventUrl, isNotBlocking);`

Maybe you have more luck with it.

**Comment by Swipe650** [comment]
Apologies, it turns out it was my privacy badger extension that suddenly started blocking content. All working again now.
